rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - rbx-2
services:
  - mongodb
matrix:
  include:
    - rvm: 2.1.2
      gemfile: gemfiles/mongoid3.0.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/mongoid3.1.gemfile
